/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DocumentComponent: typeof import('./src/components/DocumentComponent.vue')['default']
    PageComponent: typeof import('./src/components/PageComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThumbnailNavigation: typeof import('./src/components/ThumbnailNavigation.vue')['default']
  }
}
